version: '3.8'

services:

  ide:
    build:
      context: ide
      args:
        - SGDK_VERSION=1.90
        - JDK_VER=11
    ports:
      - 8080:8080
    working_dir: /workdir
    volumes:
      - shared-volume:/workdir

  gens:
    build:
      context: gens
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - ROM_PATH=docs/roms/out/rom.bin
    volumes:
      - shared-volume:/opt/wasm-genplus/docs/roms

  retroarch:
    build:
      context: retroarch
      args:
        - RETROARCH_TYPE=stable
        - RETROARCH_VERSION=1.16.0
    ports:
      - 8082:80
    restart: unless-stopped
    working_dir: /workdir
    volumes:
      - shared-volume:/workdir

volumes:
  shared-volume: