version: '3.8'

services:

  ide:
    build:
      dockerfile: Dockerfile.ide
      args:
        - SGDK_VERSION=1.90
        - JDK_VER=11
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
    working_dir: /workdir
    volumes:
      - shared-volume:/workdir

  gens:
    build:
      dockerfile: Dockerfile.gens
    ports:
      - 9000:9000
    environment:
      - ROM_PATH=docs/roms/out/rom.bin
    volumes:
      - shared-volume:/opt/wasm-genplus/docs/roms

  retroarch:
    build:
      context: .
      dockerfile: Dockerfile.retroarch
      args:
        - RETROARCH_TYPE=stable
        - RETROARCH_VERSION=1.16.0
    ports:
      - 7070:80
    restart: unless-stopped
    working_dir: /workdir
    volumes:
      - shared-volume:/workdir

volumes:
  shared-volume: